"""feat: add unique constraint to the combination of music title and artist

Revision ID: 32aa130eb819
Revises: 4655249c371a
Create Date: 2025-02-23 18:43:06.002898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32aa130eb819'
down_revision: Union[str, None] = '4655249c371a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('_title_artist_uc', 'musics', ['title', 'artist'])
    op.create_index(op.f('ix_musics_artist'), 'musics', ['artist'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_musics_artist'), table_name='musics')
    op.drop_constraint('_title_artist_uc', 'musics', type_='unique')
    # ### end Alembic commands ###
