"""fix: missing tables ralations and added_by at music table

Revision ID: 5c897f66d286
Revises: a85685923d55
Create Date: 2025-02-23 16:02:43.320606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c897f66d286'
down_revision: Union[str, None] = 'a85685923d55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('playlist_music',
    sa.Column('playlist_id', sa.Integer(), nullable=False),
    sa.Column('music_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['music_id'], ['musics.id'], ),
    sa.ForeignKeyConstraint(['playlist_id'], ['playlists.id'], ),
    sa.PrimaryKeyConstraint('playlist_id', 'music_id')
    )
    op.add_column('musics', sa.Column('added_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'musics', 'users', ['added_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'musics', type_='foreignkey')
    op.drop_column('musics', 'added_by')
    op.drop_table('playlist_music')
    # ### end Alembic commands ###
