"""feat: add private column to playlist table

Revision ID: 636bd68c5cbb
Revises: ab6d6a6cf9bb
Create Date: 2025-03-02 16:19:48.043613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '636bd68c5cbb'
down_revision: Union[str, None] = 'ab6d6a6cf9bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('playlists', sa.Column('private', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('playlists', 'private')
    # ### end Alembic commands ###
