"""fix: user music relation with the same name as reference column

Revision ID: ab6d6a6cf9bb
Revises: c1e3aa9dc9ad
Create Date: 2025-03-02 13:38:51.180104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab6d6a6cf9bb'
down_revision: Union[str, None] = 'c1e3aa9dc9ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('musics', sa.Column('added_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'musics', 'users', ['added_by'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'musics', type_='foreignkey')
    op.drop_column('musics', 'added_by')
    # ### end Alembic commands ###
