"""Recreate all migrations

Revision ID: c1e3aa9dc9ad
Revises: 
Create Date: 2025-03-01 18:47:18.480562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1e3aa9dc9ad'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_music')
    op.drop_constraint('musics_added_by_fkey', 'musics', type_='foreignkey')
    op.drop_column('musics', 'added_by')
    op.drop_constraint('playlist_music_playlist_id_fkey', 'playlist_music', type_='foreignkey')
    op.drop_constraint('playlist_music_music_id_fkey', 'playlist_music', type_='foreignkey')
    op.create_foreign_key(None, 'playlist_music', 'musics', ['music_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'playlist_music', 'playlists', ['playlist_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('playlists_owner_id_fkey', 'playlists', type_='foreignkey')
    op.create_foreign_key(None, 'playlists', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'playlists', type_='foreignkey')
    op.create_foreign_key('playlists_owner_id_fkey', 'playlists', 'users', ['owner_id'], ['id'])
    op.drop_constraint(None, 'playlist_music', type_='foreignkey')
    op.drop_constraint(None, 'playlist_music', type_='foreignkey')
    op.create_foreign_key('playlist_music_music_id_fkey', 'playlist_music', 'musics', ['music_id'], ['id'])
    op.create_foreign_key('playlist_music_playlist_id_fkey', 'playlist_music', 'playlists', ['playlist_id'], ['id'])
    op.add_column('musics', sa.Column('added_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('musics_added_by_fkey', 'musics', 'users', ['added_by'], ['id'])
    op.create_table('user_music',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('music_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['music_id'], ['musics.id'], name='user_music_music_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_music_user_id_fkey'),
    sa.PrimaryKeyConstraint('user_id', 'music_id', name='user_music_pkey')
    )
    # ### end Alembic commands ###
